---
- name: "Up | nginx-proxy"
  docker_service:
    project_name: nginx-proxy
    definition:
      version: '2'
      services:
        nginx-proxy:
          image: jwilder/nginx-proxy
          container_name: nginx-proxy
          privileged: true #add
          tty: false #add
          ports:
            - 80:80
            - 443:443
          volumes:
            - /etc/nginx/vhost.d
            - /usr/share/nginx/html
            - /srv/nginx-proxy/etc/nginx/certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
          restart: always
        letsencrypt-nginx-proxy-companion:
          image: jrcs/letsencrypt-nginx-proxy-companion
          container_name: nginx-letsencrypt
          privileged: true #add
          tty: false #add
          volumes:
            - /srv/nginx-proxy/etc/nginx/certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
          volumes_from:
            - nginx-proxy
          depends_on:
            - nginx-proxy
          restart: always
