---
- name: "copy docker-compose.yml"
  copy: 
    src: "{{ src_dir }}"
    dest: "{{ dst_dir }}"

- name: "docker-compose up -d"
  docker_service:
    project_src: "{{ dst_dir }}/{{ service_name }}"
    state: present
