version: '2'
services:
 gitlab:
  image: gitlab/gitlab-ce:8.12.4-ce.0
  container_name : gitlab-httpd
  hostname: git.tmucloud.com
  environment:
    VIRTUAL_HOST: git.tmucloud.com
    VIRTUAL_PORT: 80
    LETSENCRYPT_HOST: git.tmucloud.com
    LETSENCRYPT_EMAIL: nm7.tr.fallen.angel@gmail.com
    LETSENCRYPT_TEST: "false"
    GITLAB_OMNIBUS_CONFIG: |

      ## GitLab URL
      ##! URL on which GitLab will be reachable.
      ##! For more details on configuring external_url see:
      ##! https://docs.gitlab.com/omnibus/settings/configuration.html#configuring-the-external-url-for-gitlab 

      external_url = 'https://git.tmucloud.com/'

      ################################################################################
      ## GitLab Nginx
      ##! Docs: https://docs.gitlab.com/omnibus/settings/nginx.html
      ################################################################################
      
      nginx['redirect_http_to_https'] = true
      nginx['ssl_certificate'] = '/etc/gitlab/ssl/git.tmucloud.com.pem'
      nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/git.tmucloud.com.key'
      #nginx['listen_port'] = 80
      #nginx['listen_https'] = false
      nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
      }

      ################################################################################
      ## Container Registry settings
      ##! Docs: https://docs.gitlab.com/ce/administration/container_registry.html
      ######################################################a##########################

      #registry_external_url 'https://registry.gitlab.tmucloud.com'


      ################################################################################
      ## gitlab.yml configuration
      ##! Docs: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/gitlab.yml.md
      ################################################################################

      gitlab_rails['time_zone'] = 'Asia/Tokyo'

      ### Email Settings
      gitlab_rails['time_zone'] = 'Asia/Tokyo'
      gitlab_rails['gitlab_email_enabled'] = true
      gitlab_rails['gitlab_email_from'] = 'gitlab_user@tmucloud.com'
      gitlab_rails['gitlab_email_reply_to'] = 'gitlab_user@tmucloud.com'
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "smtp.gmail.com"
      gitlab_rails['smtp_port'] = 587
      gitlab_rails['smtp_user_name'] = "googleUSER"
      gitlab_rails['smtp_password'] = "googlePASSWD"
      gitlab_rails['smtp_domain'] = "smtp.gmail.com"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = false
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'

      ### GitLab CI email server settings
      #gitlab_ci['gitlab_ci_email_from'] = 'notification.tmucloud@gmail.com'
      #gitlab_ci['gitlab_ci_support_email'] = 'notification.tmucloud@gmail.com'
      # gitlab_ci['gitlab_ci_all_broken_builds'] = true
      # gitlab_ci['gitlab_ci_add_pusher'] = true

      gitlab_rails['backup_keep_time'] = '600'
      gitlab_workhorse['enable'] = true
      gitlab_workhorse['listen_network'] = "tcp"
      gitlab_workhorse['listen_addr'] = "127.0.0.1:8181"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /srv/ngix-proxy/etc/nginx/certs/git.tmucloud.com/:/etc/gitlab/ssl/
  volumes_from:
    - data
  ports:
    - "80"
    - "10022:22"
    - "443"
    - "587:587"
  restart: always
 gitlab-runner:
  image: gitlab/gitlab-runner:latest
  container_name : gitlab-runner
  volumes_from:
    - data
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
 data:
  image: busybox
  container_name: gitlab-data
  volumes:
    - /var/log/gitlab
    - /var/opt/gitlab
    - /etc/gitlab
    - /etc/gitlab-runner
networks:
  default:
    external:
      name: nginx-proxy_default
